# Generated by Django 3.2.16 on 2023-01-28 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookappointment',
            name='approved',
        ),
        migrations.AlterField(
            model_name='bookappointment',
            name='time_for_visit',
            field=models.TimeField(default=datetime.time(10, 0)),
        ),
    ]
